#the image variable should come from .bashrc setup
steps:
  - id: docker-build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t 
      - ${_IMAGE}
      - '.'

  - id: docker-push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE}

  - id: django-collectstatic
    name: ${_IMAGE}
    args: 
      - bash
      - -c
      - python3 manage.py collectstatic --noinput

  - id: deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - ${_SERVICE_NAME}
      - --platform=managed
      - --image=${_IMAGE}
      - --region=${_REGION}
      - --service-account=${_SERVICE_ACCOUNT}
      - --min-instances=0
      - --max-instances=2

  - id: go-live
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - services
      - update-traffic
      - ${_SERVICE_NAME}
      - --region=${_REGION}
      - --to-latest

images:
  - ${_IMAGE}