#the image variable should come from .bashrc setup
steps:
  - id: npm-build
    name: node
    entrypoint: bash
    args:
      - -c
      - |
        npm install webpack webpack-cli \
        && npm run build

  - id: docker-build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t 
      - ${_IMAGE}
      - '.'

  - id: docker-push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE}

  - id: django-collectstatic
    name: ${_IMAGE}
    args: 
      - bash
      - -c
      - |
        if [[ ${_STATIC_DEPLOY} = 'full' ]]
        then python3 manage.py collectstatic --noinput
        else python3 manage.py collectstatic --noinput -i wagtail*/** -i rest_framework/** -i admin/**
        fi

  - id: deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - ${_SERVICE_NAME}
      - --platform=managed
      - --image=${_IMAGE}
      - --region=${_REGION}
      - --service-account=${_SERVICE_ACCOUNT}
      - --min-instances=0
      - --max-instances=2

images:
  - ${_IMAGE}
