# Generated by Django 3.2.6 on 2021-08-08 06:59

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insightpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='milestonepage',
            name='description',
        ),
        migrations.AddField(
            model_name='individualpage',
            name='about',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='insightpage',
            name='body',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='journeypage',
            name='body',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='lifepage',
            name='body',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='milestonepage',
            name='body',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='momentpage',
            name='body',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='perspectivepage',
            name='body',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='body',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='milestonepage',
            name='objective',
            field=models.TextField(default=''),
        ),
    ]
