# Generated by Django 3.2.6 on 2021-08-08 07:10

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210808_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualpage',
            name='email',
            field=models.EmailField(default='abc@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualpage',
            name='first_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualpage',
            name='last_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualpage',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
