# Generated by Django 3.2.6 on 2021-08-08 07:14

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210808_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualpage',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank='True', max_length=128, null=True, region=None),
        ),
    ]
