# Generated by Django 3.2.6 on 2021-08-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_individualpage_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightpage',
            name='perspectives',
            field=models.ManyToManyField(to='blog.PerspectivePage'),
        ),
        migrations.AddField(
            model_name='perspectivepage',
            name='name',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
