# Generated by Django 3.2.6 on 2021-08-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210808_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightpage',
            name='perspectives',
            field=models.ManyToManyField(blank=True, to='blog.PerspectivePage'),
        ),
    ]
