# Generated by Django 3.2.6 on 2021-08-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_insightpage_perspectives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightpage',
            name='perspectives',
            field=models.ManyToManyField(blank=True, related_name='related_insights', to='blog.PerspectivePage'),
        ),
    ]
