# Generated by Django 3.2.6 on 2021-08-08 09:25

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_insightpage_perspectives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightpage',
            name='perspectives',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='related_insights', to='blog.PerspectivePage'),
        ),
    ]
