# Generated by Django 3.2.16 on 2022-12-31 01:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('blog', '0008_alter_insightpage_perspectives'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('body', wagtail.core.fields.RichTextField(default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TopicPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.core.fields.RichTextField(default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='journeypage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='lifepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='milestonepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='momentpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='perspectivepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='InsightPage',
        ),
        migrations.DeleteModel(
            name='JourneyPage',
        ),
        migrations.DeleteModel(
            name='LifePage',
        ),
        migrations.DeleteModel(
            name='MilestonePage',
        ),
        migrations.DeleteModel(
            name='MomentPage',
        ),
        migrations.DeleteModel(
            name='PerspectivePage',
        ),
        migrations.DeleteModel(
            name='ProjectPage',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='topics',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='related_topics', to='blog.TopicPage'),
        ),
    ]
