# Generated by Django 3.2.16 on 2022-12-31 03:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20221231_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
