# Generated by Django 3.2.16 on 2022-12-31 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_articlepage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
