# Generated by Django 3.2.16 on 2022-12-31 03:52

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_topicpage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
    ]
