# Generated by Django 3.2.16 on 2022-12-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_articlepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='individualpage',
            name='about',
            field=models.TextField(default=''),
        ),
    ]
