# Generated by Django 3.2.16 on 2023-01-01 05:11

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20221231_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='individualpage',
            name='about',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
    ]
