# Generated by Django 3.2.16 on 2023-01-02 08:34

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_individualpage_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='body',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='content',
            field=wagtail.core.fields.StreamField([('markdown', wagtail.core.blocks.CharBlock()), ('image_with_caption', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True),
        ),
    ]
